### ISSUE TITLE
Missing tags for versions greater than 2.0.6

### ISSUE THREAD

**Issue by rrialq** [OpenIdentityPlatform/commons#38]
There is no tags greater than 2.0.6, but in Maven repository I can find versions 2.0.7-2.0.12, and thgere is no releases in Github greater than 2.0.0.

Is there any reason for not tagging neither releasing those versions?
It is extrange for me.

**Comment by vharseko** [comment]
https://github.com/OpenIdentityPlatform/commons/tags
